Repository openhorizonrobotics/mapmit, pull requests merged in 2025-03, with the labels that each got.

#44 Fix: Document CORS Issue and Local Development Setup
  README.md
Labels: documentation

#45 Enhanced webmap
  webmap/index.html
  webmap/script.js
  webmap/styles.css
Labels: enhancement

#49 Implementing location detection and tracking and dynamic compass
  .idea/.gitignore
  .idea/mapmit.iml
  .idea/modules.xml
  .idea/vcs.xml
  webmap/index.html
  webmap/script.js
  webmap/styles.css
Labels: good first issue

#50 Webmap v2.0
  webmap/data/Academic Blocks.geojson
  webmap/data/Academic_Blocks.geojson
  webmap/data/Academic_Blocks.qmd
  webmap/data/Grasscover.geojson
  webmap/data/Grasscover.qmd
  webmap/data/Hostels.geojson
  webmap/data/Hostels.qmd
  webmap/data/Mess.geojson
  webmap/data/Mess.qmd
  webmap/data/Others.geojson
  webmap/data/Others.qmd
  webmap/data/Parking.geojson
  webmap/data/Parking.qmd
  webmap/data/Shops.geojson
  webmap/data/Shops.qmd
  webmap/data/Sports.geojson
  webmap/data/Sports.qmd
  webmap/data/Trees.geojson
  webmap/data/Trees.qmd
  webmap/data/Under_Construction.geojson
  webmap/data/Under_Construction.qmd
  webmap/data/circles.qmd
  webmap/data/roads_main.geojson
  webmap/data/roads_main.qmd
  webmap/data/roads_second.geojson
  webmap/data/roads_second.qmd
  webmap/data/temple.qmd
  webmap/data/walkways.geojson
  webmap/data/walkways.qmd
  webmap/script.js
Labels: enhancement
